name: Hello World 01
on:
  - workflow_dispatch
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo hello, world!
      - name: Hello 2
        run: echo hello 2
        
