name: Hello World 01
on:
  workflow_dispatch:
    inputs:
      message:
        required: true
        default: message default

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo hello, world!
      - name: Hello 2
        run: echo hello 2
      - name: Echo input
        run: "echo message: ${{ github.event.inputs.message }}"

